# src/models/health/health_scoring.py
"""Health scoring utilities (Part 2).

This module converts the ``anomaly_score`` generated by the IsolationForest
(Part 1) into a deterministic, reproducible ``health_score`` in ``[0, 100]``
(``100`` = healthiest, ``0`` = most degraded) and a categorical
``health_status`` using exactly the labels ``NORMAL``, ``WARNING``,
``CRITICAL``.

Normalization formula
---------------------
health_score = clip(
    (ANOMALY_SCORE_MAX - anomaly_score) / (ANOMALY_SCORE_MAX - ANOMALY_SCORE_MIN) * 100,
    0, 100,
)

The bounds ``ANOMALY_SCORE_MIN`` / ``ANOMALY_SCORE_MAX`` are fixed constants
from :pymod:`src.models.health.health_config` (0.5th/99.5th percentiles of the
Part 1 training scores), so the same scale is applied to new data without
re-fitting.  Higher anomaly_score -> lower health_score.

Status thresholds
-----------------
- ``NORMAL``   : ``health_score >= 70``
- ``WARNING``  : ``40 <= health_score < 70``
- ``CRITICAL`` : ``health_score < 40``

All functions are reusable: :func:`compute_health` accepts any DataFrame
containing ``unit``, ``cycle`` and an ``anomaly_score`` column and returns a
new DataFrame with ``health_score`` and ``health_status`` appended.
"""

from __future__ import annotations

import pathlib
from typing import Optional, Tuple

import numpy as np
import pandas as pd

from .health_config import (
    ANOMALY_SCORE_MAX,
    ANOMALY_SCORE_MIN,
    HEALTH_NORMAL_THRESHOLD,
    HEALTH_SCORE_MAX,
    HEALTH_SCORE_MIN,
    HEALTH_STATUS_CRITICAL,
    HEALTH_STATUS_NORMAL,
    HEALTH_STATUS_WARNING,
    HEALTH_WARNING_THRESHOLD,
)

# ---------------------------------------------------------------------------
# Core transformation utilities
# ---------------------------------------------------------------------------


def normalize_anomaly(
    anomaly_series: pd.Series,
    min_anomaly: Optional[float] = None,
    max_anomaly: Optional[float] = None,
) -> pd.Series:
    """Normalize an anomaly-score series to a ``[0, 100]`` health score.

    Parameters
    ----------
    anomaly_series:
        Raw ``anomaly_score`` values (higher = more abnormal).
    min_anomaly, max_anomaly:
        Reference bounds for the linear scaling.  When ``None`` the fixed
        constants ``ANOMALY_SCORE_MIN`` / ``ANOMALY_SCORE_MAX`` from
        :pymod:`health_config` are used, which keeps the score reproducible
        across datasets.

    Returns
    -------
    Series of health scores in ``[0, 100]``; ``100`` = healthiest.
    """
    if min_anomaly is None:
        min_anomaly = ANOMALY_SCORE_MIN
    if max_anomaly is None:
        max_anomaly = ANOMALY_SCORE_MAX
    if max_anomaly == min_anomaly:
        return pd.Series([HEALTH_SCORE_MAX] * len(anomaly_series), index=anomaly_series.index)

    # Use a logistic mapping to prevent valid anomaly values from collapsing to exactly 0.
    # The mapping is anchored to preserve the original 70 and 40 status cut-offs
    # (which occur at 30% and 70% of the linear range from min_anomaly to max_anomaly).
    k = np.log(3.5) / (0.3 * (max_anomaly - min_anomaly))
    A0 = (max_anomaly - 0.4 * (max_anomaly - min_anomaly)) - np.log(1.5) / k

    exponent = np.clip(k * (anomaly_series - A0), a_min=-700, a_max=700)
    score = HEALTH_SCORE_MAX / (1.0 + np.exp(exponent))
    return score


def assign_status(health_score_series: pd.Series) -> pd.Series:
    """Assign a categorical health status from a health-score series.

    Thresholds are defined in :pymod:`health_config`.  The function returns
    exactly ``NORMAL``, ``WARNING`` or ``CRITICAL``.
    """
    conditions = [
        health_score_series >= HEALTH_NORMAL_THRESHOLD,
        health_score_series >= HEALTH_WARNING_THRESHOLD,
    ]
    choices = [HEALTH_STATUS_NORMAL, HEALTH_STATUS_WARNING]
    return pd.Series(
        np.select(conditions, choices, default=HEALTH_STATUS_CRITICAL),
        index=health_score_series.index,
    )


def compute_reference_bounds(
    df: pd.DataFrame,
    anomaly_col: str = "anomaly_score",
    percentile_min: float = 0.5,
    percentile_max: float = 99.5,
) -> Tuple[float, float]:
    """Recompute the reference bounds from a reference DataFrame.

    This documents the procedure that produced the fixed constants in
    :pymod:`health_config`; the runtime pipeline uses those constants directly.
    """
    series = df[anomaly_col]
    return (
        float(np.percentile(series, percentile_min)),
        float(np.percentile(series, percentile_max)),
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def compute_health(
    df: pd.DataFrame,
    anomaly_col: str = "anomaly_score",
    min_anomaly: Optional[float] = None,
    max_anomaly: Optional[float] = None,
) -> pd.DataFrame:
    """Compute ``health_score`` and ``health_status`` for a DataFrame.

    Parameters
    ----------
    df:
        Must contain the identifier columns ``unit`` and ``cycle`` and the
        specified ``anomaly_col``.
    anomaly_col:
        Name of the column holding the Part 1 anomaly scores.
    min_anomaly, max_anomaly:
        Optional reference bounds overriding the fixed config defaults.

    Returns
    -------
    A **new** DataFrame with the columns

    - ``unit``
    - ``cycle``
    - ``anomaly_score``
    - ``health_score``  (float, ``[0, 100]``)
    - ``health_status`` (NORMAL / WARNING / CRITICAL)

    The reference bounds actually used are stored in ``attrs`` for auditability.
    """
    if anomaly_col not in df.columns:
        raise KeyError(f"Column '{anomaly_col}' not found in input DataFrame.")
    if min_anomaly is None:
        min_anomaly = ANOMALY_SCORE_MIN
    if max_anomaly is None:
        max_anomaly = ANOMALY_SCORE_MAX

    health_score = normalize_anomaly(df[anomaly_col], min_anomaly, max_anomaly)
    health_status = assign_status(health_score)

    result = df.copy()
    result["health_score"] = health_score.round(2)
    result["health_status"] = health_status

    # Reorder columns: unit, cycle, remaining originals, then health columns.
    ordered = []
    for col in ["unit", "cycle"]:
        if col in result.columns:
            ordered.append(col)
    ordered.extend(c for c in result.columns if c not in ordered and c not in ("health_score", "health_status"))
    ordered.extend(["health_score", "health_status"])
    result = result[ordered]

    result.attrs["anomaly_min"] = min_anomaly
    result.attrs["anomaly_max"] = max_anomaly
    return result


# ---------------------------------------------------------------------------
# Convenience script for quick verification on the existing Part 1 output
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    _PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[3]
    _SCORES_PATH = _PROJECT_ROOT / "src" / "models" / "health" / "anomaly_scores.csv"
    _OUT_PATH = _PROJECT_ROOT / "src" / "models" / "health" / "health_scores.csv"

    scores_df = pd.read_csv(_SCORES_PATH)
    health_df = compute_health(scores_df)
    health_df.to_csv(_OUT_PATH, index=False)

    counts = health_df["health_status"].value_counts()
    total = len(health_df)
    print(f"Health scores written to {_OUT_PATH}")
    print(f"Total rows: {total}")
    for status in [HEALTH_STATUS_NORMAL, HEALTH_STATUS_WARNING, HEALTH_STATUS_CRITICAL]:
        cnt = counts.get(status, 0)
        print(f"{status}: {cnt} ({cnt / total * 100:.2f}%)")
    print("Sample rows:")
    print(health_df.head())